### ISSUE TITLE
Title in YAML header

### ISSUE THREAD

**Issue by nachti** [jimhester/knitrBootstrap#173] opened 2015-04-07 14:35 UTC
Trying to get a title using `title` in YAML (as described [here](https://github.com/jimhester/knitrBootstrap#yaml-front-matter)) is not successful -- I can't find the title anywhere (`rmarkdown::render('test.Rmd', 'knitrBootstrap::bootstrap_document')`).
```
---
output:
  knitrBootstrap::bootstrap_document:
    title: "Test file"
    theme: amelia
    highlight: sunburst
    theme.chooser: TRUE
    highlight.chooser: TRUE
---

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents.
```

If I use the following lines instead to knit a *standard* html document (`rmarkdown::render('$(FILE).Rmd', 'html_document')`), everything is fine:

```
---
title: "Test file"
author: "Gerhard Nachtmann"
date: '`r Sys.Date()`'
output:
  html_document:
    theme: united
    toc: yes
  pdf_document:
    toc: yes
  knitrBootstrap::bootstrap_document:
#    title: 'Test file' # does not work
    theme: 'readable' # boot_style
    highlight: 'google code' # code_style
---

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents.
```

Do you know what's wrong there?
~g

**Comment by humburg** [comment] 2015-07-23 16:26
It appears that the title is only added to the header but not the body. If you look at the generated HTML file you should be able to see a `<title>` tag with the specified title. Your browser will should display that as the title of the window/tab. It looks like that is the intended behaviour but it would indeed be nice to get this also included in the body of the page, maybe wrapped in a *.page-header* div.

**Comment by nachti** [comment] 2015-07-24 09:07
It's not just the title - author and date are also missing in the body of the HTML document.
Peter, the `<title>` is correct, but it shouldn't differ from the standard `html_document`.
I generate my outputs (`html_document` and `knitrBootstrap::bootstrap_document` and pdf_document) from the same source using a makefile. If I insert tille & co extra after the YAML header, it would be twice in the other documents ...

**Comment by humburg** [comment] 2015-07-24 10:37
I completely agree, that information should be included in the body of the generated web page, just like with the other formats. Using the version of *knitrBootstrap* from #68 it seems that the title, author and date *are* added to the page but are hidden. Not sure what the reasoning behind this is.

**Comment by humburg** [comment] 2015-07-29 15:23
This now works in #68 so this issue can probably be closed.

**Comment by nachti** [comment] 2015-07-30 14:00
@humburg:
After installing knitrBootstrap using `devtools::install_github('jimhester/knitrBootstrap@rmarkdown_template')` I get the following Error

```
rmarkdown::render('docu.Rmd', 'knitrBootstrap::bootstrap_document', output_file = 'docu_bt.html')
Error in match(x, table, nomatch = 0L) :
  argument "pandoc_args" is missing, with no default
Calls: <Anonymous> ... html_document_base -> check_pandoc_args -> %in% -> match
Execution halted
```

**Comment by humburg** [comment] 2015-07-30 14:26
@nachti:
Looks like a recent change I submitted broke that, apologies. It should now be fixed.

**Comment by nachti** [comment] 2015-07-30 14:31
@humburg 
Thanks. Title etc. are working now using your branch, but the style is quite different to the *original*:
Margins cut the text (particularly code blocks) and the dynamic TOC at the right side is missing.

**Comment by humburg** [comment] 2015-07-30 15:26
@nachti 
It isn't really *my* branch. The way I understand it is basically the development branch for the next version of knitrBootstrap (and existed long before I started contributing to it). This now builds on top of *rmarkdown::html_document* so some things have changed a bit (the discussion on #68 has some more details). The TOC is still there though. Are you including a *toc* option in your yaml front matter?

It is true that the code blocks are slightly wider than the text (15px each side, I think). The easiest fix for that would be to include some custom CSS adjust the styling to something you find more appealing.

**Comment by nachti** [comment] 2015-07-30 15:47
I see. Thanks for the info. If I include the TOC in the YAML header explicitly, it's present in the output HTML, but on the left side overlaying the text. This was quite better in the master branch.

**Comment by jimhester** [comment] 2015-07-30 15:49
Could you make a gist with an example Rmd file that exhibits the issues you are describing?  I will figure out where the error is.

**Comment by nachti** [comment] 2015-07-31 09:28
@jimhester 
I found out, that the problem is caused by a code block within an enumeration.
https://gist.github.com/nachti/8b495f1d25b34335de8a
If I insert a blank line before the code block (after *Some code*) it is working, but the block is still not indented correctly. Using `html_document`, everything is as expected.

Another thing: In my git repo I found a folder `<filename>_files` containing the pictures, styles etc., which is different to the master branch. Is there a possibility to include these stuff again (`self_contained: true` - which should be the default - did not work)

**Comment by ivannp** [comment] 2016-02-01 00:59
Title still doesn't show up. All the examples use a title coming from the document itself, aka:

# Cars example #179 

Try using "title" in the YAML, and you will see, the title doesn't show up. With regular knitr, the following works:

---
title: "KnitrBootstrap Test"
author: Holly Molly
date: "January 31, 1016"
output: html_document
---

![knitr-good](https://cloud.githubusercontent.com/assets/1331156/12706506/b662a8bc-c83b-11e5-823c-adc07dcab366.png)

With knitrBootstrap, I can't find a variation that works. For example:

---
author: Holly Molly
date: "January 31, 1016"
output:
  knitrBootstrap::bootstrap_document:
    title: "KnitrBootstrap Test"
    theme: amelia
    highlight: sunburst
    theme.chooser: TRUE
    highlight.chooser: TRUE
---

Produces no title, no author nothing.

Tried the latest version as well as the CRAN version.

**Comment by humburg** [comment] 2016-02-01 01:22
@ivannp, could you confirm whether you have tried this with the *rmarkdown_template* branch? That's  what I would consider the latest version but that isn't very obvious so you may have tried the current *master*? My impression is that this does work in *rmarkdown_template* but I haven't looked at it in a while.

**Comment by ivannp** [comment] 2016-02-01 03:14
Could you be more specific with the steps? I installed the _rmarkdown_template_ branch using:

    install_github('jimhester/knitrBootstrap',ref='rmarkdown_template')

No change in the output. I am trying all these in RStudio, by calling the knitting via the GUI.

**Comment by humburg** [comment] 2016-02-01 04:36
That sounds fine. Doing exactly the same procedure to install and knit I get the desired output using a YAML block like this:

```
---
title: "Test file"
author: Tester
output:
  knitrBootstrap::bootstrap_document:
    toc: true
    theme: amelia
    highlight: sunburst
---
```

A complete file for testing is here:
https://gist.github.com/humburg/098532001c6ada6466fb

Note that the title and author have to be at the top level *not* under `output`. This is consistent with the documentation of the *rmarkdown_template* branch (but that is easy to overlook).

@jimhester, maybe it would make sense to make *rmarkdown_template* the default branch until it is merged into master?

**Comment by ivannp** [comment] 2016-02-01 04:44
Great, this worked on the latest version. Thanks!

**Comment by jimhester** [comment] 2016-02-02 13:38
@humburg thank you for debugging this and providing a fix.

The reason I have not merged _rmarkdown_tempate_ into master is there are still some features missing from the branch which I unfortunately do not have time to address. https://github.com/jimhester/knitrBootstrap/pull/68#issuecomment-93811297 lists the main sticking points in my opinion.

**Comment by humburg** [comment] 2016-02-02 21:47
@jimhester I understand that *rmarkdown_template* isn't really done yet and it seems very reasonable not to merge it into *master* until it is. However, in some respects it seems preferable to the latest release, even in its current state. Considering that it might be a while until it is ready for a release I thought it might be helpful to advertise it more prominently to new users. I know it took me a while to figure out that it is the *rmarkdown_template* branch I want to use.

**Closed** 2016-03-03 21:31 UTC
